DROP VIEW USERS CASCADE CONSTRAINTS;
DROP VIEW PERFORMANCE CASCADE CONSTRAINTS;
DROP VIEW RESERVATION CASCADE CONSTRAINTS;
DROP VIEW ROLE CASCADE CONSTRAINTS;
DROP VIEW THEATRE CASCADE CONSTRAINTS;

DROP TABLE USER_TABLE CASCADE CONSTRAINTS;
DROP TABLE PERFORMANCE_TABLE CASCADE CONSTRAINTS;
DROP TABLE RESERVATION_TABLE CASCADE CONSTRAINTS;
DROP TABLE ROLE_TABLE CASCADE CONSTRAINTS;
DROP TABLE THEATRE_TABLE CASCADE CONSTRAINTS;

DROP SEQUENCE USER_SEQ;
DROP SEQUENCE PERFORMANCE_SEQ;
DROP SEQUENCE RESERVATION_SEQ;
DROP SEQUENCE ROLE_SEQ; 
DROP SEQUENCE THEATRE_SEQUENCE;
